apiVersion: apps/v1
kind: Deployment
metadata:
  name: denet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: denet
  template:
    metadata:
      labels:
        app: denet
    spec:
      containers:
      - image: okteto.dev/denet:latest
        name: denet
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "0f5641e2-f0e9-d7d7-aa9c-cce59d37c0c3"
        - name: Vless_Path
          value: "/app"
        - name: Vmess_UUID
          value: "0f5641e2-f0e9-d7d7-aa9c-cce59d37c0c3"
        - name: Vmess_Path
          value: "/app"
        - name: Share_Path
          value: "/v2link"
